###################################################
#                                                 #
#         TURN ON LIVING ROOM LAMP AT SUNSET      #
#                                                 #
###################################################
- alias: Living Room Lamp - Sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
    - platform: state
      entity_id: group.family_devices
      to: 'home'
  condition:
    - condition: state
      entity_id: group.family_devices
      state: 'home'
    - condition: sun 
      after: sunset 
      after_offset: "-00:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.plugin_1