###################################################
#                                                 #
#                   AWAY MODE                     #
#                                                 #
###################################################
- alias: Away Mode
  trigger:
    platform: state
    entity_id: group.family_devices
    to: 'not_home'
  action:
    - service: switch.turn_off
      data:
        entity_id: all
    - service: cover.close_cover
      data:
        entity_id: all
    - service: lock.lock
      data:
        entity_id: all
    - service: nest.set_away_mode
      data:
        away_mode: away