###################################################
#                                                 #
#                      AP01                       #
#                                                 #
###################################################
- alias: AP01 Offline
  trigger:
    platform: state
    entity_id: binary_sensor.ap01
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "AP01 is offline!"
- alias: AP01 Online
  trigger:
    platform: state
    entity_id: binary_sensor.ap01
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "AP01 is online!"

###################################################
#                                                 #
#                     HP ILO                      #
#                                                 #
###################################################
- alias: HP ILO Offline
  trigger:
    platform: state
    entity_id: binary_sensor.hp_ilo
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "HP iLO is offline!"
- alias: HV01 Online
  trigger:
    platform: state
    entity_id: binary_sensor.hp_ilo
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "HP iLO is online!"

###################################################
#                                                 #
#                     UNRAID                      #
#                                                 #
###################################################
- alias: UNRAID Offline
  trigger:
    platform: state
    entity_id: binary_sensor.unraid
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Unraid is offline!"
- alias: UNRAID Online
  trigger:
    platform: state
    entity_id: binary_sensor.unraid
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Unraid is online!"
        
###################################################
#                                                 #
#                    OPENVPN                      #
#                                                 #
###################################################
- alias: OPENVPN Offline
  trigger:
    platform: state
    entity_id: binary_sensor.openvpn
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "OpenVPN is offline!"
- alias: OPENVPN Online
  trigger:
    platform: state
    entity_id: binary_sensor.openvpn
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "OpenVPN is online!"

###################################################
#                                                 #
#                     UNIFI                       #
#                                                 #
###################################################
- alias: UNIFI Offline
  trigger:
    platform: state
    entity_id: binary_sensor.unifi
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Unifi is offline!"
- alias: UNIFI Online
  trigger:
    platform: state
    entity_id: binary_sensor.unifi
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Unifi is online!"

###################################################
#                                                 #
#                     PIHOLE                      #
#                                                 #
###################################################
- alias: PIHOLE Offline
  trigger:
    platform: state
    entity_id: binary_sensor.pihole
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Pi-Hole is offline!"
- alias: PIHOLE Online
  trigger:
    platform: state
    entity_id: binary_sensor.pihole
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Pi-Hole is online!"

###################################################
#                                                 #
#                      PLEX                       #
#                                                 #
###################################################
- alias: PLEX Offline
  trigger:
    platform: state
    entity_id: binary_sensor.plex
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Plex is offline!"
- alias: PLEX Online
  trigger:
    platform: state
    entity_id: binary_sensor.plex
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Plex is online!"

###################################################
#                                                 #
#                   GARAGE DOOR                   #
#                                                 #
###################################################
- alias: Garage Door Open
  trigger:
    platform: state
    entity_id: cover.linear_gd00z4_garage_door_opener
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: device_tracker.corys_iphone
    state: 'not_home'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Garage door has opened!"
- alias: Garage Door Closed
  trigger:
    platform: state
    entity_id: cover.linear_gd00z4_garage_door_opener
    from: 'open'
    to: 'closed'
  condition:
    condition: state
    entity_id: device_tracker.corys_iphone
    state: 'not_home'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Garage door has closed!"