###################################################
#                                                 #
#                      AP01                       #
#                                                 #
###################################################
- alias: AP01 Offline
  trigger:
    platform: state
    entity_id: binary_sensor.ap01
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "AP01 is offline!"
- alias: AP01 Online
  trigger:
    platform: state
    entity_id: binary_sensor.ap01
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "AP01 is online!"

###################################################
#                                                 #
#                      HV01                       #
#                                                 #
###################################################
- alias: HV01 Offline
  trigger:
    platform: state
    entity_id: binary_sensor.hv01
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "HV01 is offline!"
- alias: HV01 Online
  trigger:
    platform: state
    entity_id: binary_sensor.hv01
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "HV01 is online!"

###################################################
#                                                 #
#                    FPMS01                       #
#                                                 #
###################################################
- alias: FPMS01 Offline
  trigger:
    platform: state
    entity_id: binary_sensor.fpms01
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "FPMS01 is offline!"
- alias: FPMS01 Online
  trigger:
    platform: state
    entity_id: binary_sensor.fpms01
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "FPMS01 is online!"

###################################################
#                                                 #
#                       UNIFI                     #
#                                                 #
###################################################
- alias: UNIFI Offline
  trigger:
    platform: state
    entity_id: binary_sensor.unifi
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "UNIFI is offline!"
- alias: UNIFI Online
  trigger:
    platform: state
    entity_id: binary_sensor.unifi
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "UNIFI is online!"

###################################################
#                                                 #
#                     PIHOLE                      #
#                                                 #
###################################################
- alias: PIHOLE Offline
  trigger:
    platform: state
    entity_id: binary_sensor.pihole
    from: 'on'
    to: 'off'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Pi-Hole is offline!"
- alias: PIHOLE Online
  trigger:
    platform: state
    entity_id: binary_sensor.pihole
    from: 'off'
    to: 'on'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Pi-Hole is online!"

###################################################
#                                                 #
#                  GARAGE DOOR                    #
#                                                 #
###################################################
- alias: Garage Door Open
  trigger:
    platform: state
    entity_id: cover.linear_gd00z4_garage_door_opener
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: device_tracker.corysiphone
    state: 'not_home'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Garage door has opened!"
- alias: Garage Door Closed
  trigger:
    platform: state
    entity_id: cover.linear_gd00z4_garage_door_opener
    from: 'open'
    to: 'closed'
  condition:
    condition: state
    entity_id: device_tracker.corysiphone
    state: 'not_home'
  action:
    - service: notify.ios_corys_iphone
      data:
        message: "Garage door has closed!"