###################################################
#                                                 #
#                   AWAY MODE                     #
#                                                 #
###################################################
- alias: Away Mode
  trigger:
    platform: state
    entity_id: group.family_devices
    to: 'not_home'
  action:
    - service: switch.turn_off
      data:
        entity_id: group.all_switches
    - service: cover.close_cover
      data:
        entity_id: group.all_covers
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'away'