###################################################
#                                                 #
#                 NEST ECO OFF                    #
#                                                 #
###################################################
#- alias: Nest to Home
#  trigger:
#    platform: state
#    entity_id: group.family_devices
#    from: 'not_home'
#    to: 'home'
#  action:
#    - service: climate.set_preset_mode
#      data:
#        entity_id: climate.living_room
#        preset_mode: 'none'

###################################################
#                                                 #
#               LIGHTS - ARRIVE HOME              #
#                                                 #
###################################################
- alias: Lights on when Arriving
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: group.home_lights