###################################################
#                                                 #
#                 NEST ECO OFF                    #
#                                                 #
###################################################
- alias: Nest to Home when Arriving
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room
        away_mode: 'off'

###################################################
#                                                 #
#          LIVING ROOM LAMP - ARRIVE HOME         #
#                                                 #
###################################################
- alias: Living Room Lamp on when Arriving
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: sun
      before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: switch.plugin_1