###################################################
#                                                 #
#                 LIGHTS - SUNSET                 #
#                                                 #
###################################################
- alias: Lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.family_devices
    state: 'home'
  action:
    service: switch.turn_on
    entity_id: switch.plugin_1

###################################################
#                                                 #
#      GARAGE DOOR OPENED - PORCH LIGHTS ON       #
#                                                 #
###################################################
- alias: Garage Door Opened/Porch Lights On
  trigger:
    platform: state
    entity_id: cover.linear_gd00z4_garage_door_opener
    to: 'open'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:15:00"
    - condition: sun
      before: sunrise
      before_offset: "-04:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.porch_lights
    - delay:
       minutes: 5
    - service: switch.turn_off
      entity_id: switch.porch_lights