###################################################
#                                                 #
#            LIVING ROOM LAMP - SUNSET            #
#                                                 #
###################################################
- alias: Living Room Lamp - Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.family_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: switch.plugin_1

###################################################
#                                                 #
#          LIVING ROOM LAMP - ARRIVE HOME         #
#                                                 #
###################################################
- alias: Living Room Lamp - Arrive Home
  trigger:
    platform: state
    entity_id: group.family_devices
    to: 'home'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: sun
      before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: switch.plugin_1

###################################################
#                                                 #
#      GARAGE DOOR OPENED - PORCH LIGHTS ON       #
#                                                 #
###################################################
- alias: Garage Door Opened - Porch Lights On
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "-04:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.porch_lights